name: Publish and Create Release for Node.js Package
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Check if NPM_AUTH_TOKEN is set in the secrets
      - name: Check if NPM_AUTH_TOKEN is set
        run: |
          if [ -z "${{ secrets.NPM_AUTH_TOKEN }}" ]; then
            echo "Error: NPM_AUTH_TOKEN is not set!"
            exit 1
          else
            echo "NPM_AUTH_TOKEN is set."
          fi

      # Extract the current version from package.json and store it in the environment
      - name: Extract package version
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

  
      # Fetch the latest version of the package from the npm registry
      - name: Fetch latest version from NPM registry
        run: |
          latest_version=$(npm show $(jq -r .name package.json) dist-tags.latest)
          if [ -z "$latest_version" ]; then
            latest_version="0.0.0"
            echo "The package does not exist in the npm registry."
          else
            echo "The package exists in the npm registry. npm package version: $latest_version"
          fi
          echo "latest_version=$latest_version" >> $GITHUB_ENV


      # Compare the versions to determine if the package should be published
      - name: Compare versions and decide whether to publish
        id: compare_versions
        run: |
          if [ "$latest_version" == "0.0.0" ]; then
            echo "Version is 0.0.0, proceeding with publish."
            echo "should_publish=true" >> $GITHUB_ENV
          elif [ "${{ env.version }}" == "$latest_version" ]; then
            echo "Version is equal to the latest version, skipping publish."
            echo "should_publish=false" >> $GITHUB_ENV
          elif [ "$(printf '%s\n' "${{ env.version }}" "$latest_version" | sort -V | head -n1)" == "$latest_version" ]; then
            echo "Current version is greater than the latest version, proceeding with publish."
            echo "should_publish=true" >> $GITHUB_ENV
          else
            echo "Current version is less than the latest version, skipping publish."
            echo "should_publish=false" >> $GITHUB_ENV
          fi


      # # Publish the package to npm if the version is newer
      - name: Publish to npm
        if: env.should_publish == 'true'
        run: |
          npm ci --include=dev
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # # Create a GitHub release if the version is newer
      - name: Create GitHub Release
        if: env.should_publish == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: "latest"
          release_name: "v${{ env.version }}"
          body: "Automatically created release for version v${{ env.version }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
